name: calculadora_bcv
description: "Calculadora de tasas del BCV, conversiones, historial y esc√°ner de precios."
publish_to: 'none'
version: 1.0.23+23

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.3
  http: ^1.6.0
  intl: ^0.20.2
  math_expressions: ^3.1.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  workmanager: ^0.9.0
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  image_picker: ^1.2.1
  photo_manager: ^3.8.3
  google_mobile_ads: ^7.0.0
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.2
  home_widget: ^0.8.1
  connectivity_plus: ^7.0.0
  showcaseview: ^3.0.0
  in_app_update: ^4.2.5
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/iconoBCV5.png"
  adaptive_icon_background: "#c9cac7"
  adaptive_icon_foreground: "assets/icon/iconoBCV5.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/iconoBCV5.png"
    background_color: "#c9cac7"
    theme_color: "#c9cac7"

flutter_native_splash:
  color: "#0A192F"
  image: "assets/splash/iconoBCV5.png"
  android_12:
    image: "assets/splash/iconoBCV5.png"
    icon_background_color: "#0A192F"

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/icon/